# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 20:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ldtk', '0002_remove_itsmzsk_zsk_gongxianzhe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itsmzsk',
            name='zsk_gongju',
        ),
        migrations.RemoveField(
            model_name='itsmzsk',
            name='zsk_jianyirenshu',
        ),
        migrations.RemoveField(
            model_name='itsmzsk',
            name='zsk_sblx',
        ),
    ]
