# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtk', '0003_auto_20170204_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='gongjuleixin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='shebeileixin',
            old_name='sblx_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='peizhiku',
            name='pz_iitem',
        ),
        migrations.RemoveField(
            model_name='shebei',
            name='sb_lx',
        ),
        migrations.AddField(
            model_name='itsmzsk',
            name='shijian',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
