# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ldtk', '0004_auto_20170205_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='gongju',
            name='leixin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.gongjuleixin'),
        ),
        migrations.AddField(
            model_name='itsmzsk',
            name='gongju',
            field=models.ManyToManyField(to='ldtk.gongju'),
        ),
        migrations.AddField(
            model_name='peizhiku',
            name='pz_iitem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.shebei'),
        ),
        migrations.AddField(
            model_name='shebei',
            name='sb_lx',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.shebeileixin'),
        ),
        migrations.AlterField(
            model_name='jifang',
            name='jf_danwei',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.yonghudanwei'),
        ),
        migrations.AlterField(
            model_name='jifang',
            name='jf_gly',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.yonghu'),
        ),
        migrations.AlterField(
            model_name='jifang',
            name='jf_weizhi',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.weizhi'),
        ),
        migrations.AlterField(
            model_name='jigui',
            name='jg_jf',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.jifang'),
        ),
        migrations.AlterField(
            model_name='xjitem',
            name='xjitem_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.fuwufanwei'),
        ),
        migrations.AlterField(
            model_name='yonghu',
            name='yh_dan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ldtk.yonghudanwei'),
        ),
    ]
