# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtk', '0005_auto_20170205_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='shebei',
            name='name',
            field=models.CharField(default='aa', max_length=100),
        ),
    ]
