# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ldtk', '0008_itsmzsk_shebei'),
    ]

    operations = [
        migrations.AddField(
            model_name='itsmzsk',
            name='fabu',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itsmzsk',
            name='shenpi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='itsmzsk',
            name='shijian',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
